dist: xenial
sudo: yes

language: python

python:
  - "3.7"

addons:
  sonarcloud:
    organization: "chidgey-github"

script:
  - nosetests --with-coverage --with-xunit --cover-xml 
  - sonar-scanner